parent_config: https://raw.githubusercontent.com/sindresorhus/swiftlint-config/main/.swiftlint.yml

disabled_rules:
  - opening_brace
  - multiline_arguments

excluded:
  - Tests Apple TV
  - Tests iOS
  - Tests macOS
